language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.2
    - nightly

codecov: true
coveralls: true

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
